var  cleanlinessImg
function preload()
{
	cleanlinessImg = createImg("cleanlinessImg.jpg")
	
}
function setup()
{
   createCanvas(displayWidth -48 , displayHeight-201)	
   background("lightblue")
   cleanlinessImg.position(600,13)
   cleanlinessImg.size(150 , 100)
}
function draw()
{
	textSize(20)
	fill("orange")
	text("Here are a few easy and effective ways you can choose to reduce your daily impact and make a world of difference:" , 10 , 140)
    textSize(20)
	fill("black")
	text("1)Bring a bag :-" , 10 , 170)
	textSize(20)
	fill("green")
	text("Remember to bring reusable bags to the grocery store or for any other shopping activities to reduce consumption of disposable bags." , 150 , 170)
    textSize(20)
	fill("black")
	text("2)Bring your own reusable cup :-" , 10 , 200)
	textSize(20)
	fill("green")
	text("Think about how many disposable cups are used every day in just your local coffee shop. Bringing a mug for your morning coffee can " , 300 , 200)
    textSize(20)
	fill("green")
	text("reduce the amount of waste you produce annually. Imagine how much waste we could reduce if we all made this simple daily change!" ,300 , 230)
    textSize(20)
	fill("black")
	text("3)Invest in a reusable water bottle :-" , 10 , 260)
    textSize(20)
	fill("green")
	text(" Acquiring a reusable water bottle would not only greatly reduce the amount of single-use plastic you use, but it would also save " , 330 , 260)
    textSize(20)
	fill("green")
	text("you money in the long run! If you’re concerned about the quality of your tap water, consider using a water filter." , 330 , 290)
    textSize(20)
	fill("black")
	text("4) Compost :-" , 10 , 320)
	textSize(20)
	fill("green")
	text("Composting at home reduces the volume of garbage sent to landfills and reduces the chance of some products becoming marine debris." , 140 , 320)
    textSize(20)
	fill("black")
	text("5) Refuse single-use items :- " , 10 , 350)
	textSize(20)
	fill("green")
	text("Take note on how often you rely on single-use items and choose to replace them with more sustainable versions. Refusing plastic straws " , 270 , 350)
    textSize(20)
	fill("green")
	text("and disposable cutlery when you go out and bringing your own containers for leftovers are a few ways you can start today." , 270 , 380)
    textSize(20)
	fill("black")
	text("6) Avoid products with microbeads :-" ,10 , 410 )
	textSize(20)
	fill("green")
	text("The three main product categories containing microbeads are face wash, body scrub and toothpaste. Read the labels when" , 340 , 410)
    textSize(20)
	fill("green")
	text("purchasing products and opt for ones that contain natural ingredients." , 340 , 440)
    textSize(20)
	fill("black")
	text("7) Make sure your waste goes to the right place :-" , 10 , 470)
    textSize(20)
	fill("green")
	text("Do your best to ensure that the waste you dispose of ends up where it should. Recycle the materials that are  " , 460 , 470)
	textSize(20)
	fill("green")
	text("recyclable in your area and make sure to reduce the likelihood of your garbage ending up in the environment " , 460 , 500)
    textSize(20)
	fill("green")
	text("by keeping a lid on your trash can when it’s outside. " , 460 , 530)
	textSize(20)
	fill("black")
	text("8) Shop in bulk :-" , 10 , 560)
	textSize(20)
	fill("green")
	text("Consider the product-to-packaging ratio when purchasing items and choose larger containers instead of multiple smaller ones. When you have the" , 168 , 560)
    textSize(20)
	fill("green")
	text("option, also consider purchasing package-free foods and household goods." , 168 , 590)
    textSize(20)
	fill("black")
	text("Cleaning up the country cannot be the sole responsibility of sweepers. Do citizens have no role in this? We have to change this mindset!!",150 , 630)

	
}  
